### ISSUE TITLE
A general rule of thumb for creating a multi-threaded SSH cracker

### ISSUE THREAD

**Issue by moimikey** [moimikey/craic#1]
# TODO
# fabric
- [ ] listen() for broadcast() to halt each pending thread
# thread
- [ ] broadcast() status to fabric() each _n_ millisecond(s)
# notes
- [ ] wordlist attack, chunked word list
# projected usage

```
-h host
-p port (default: 22)
-u username
-c combo list (ignores -u and -w)
-w wordlist (used in conjunction with -u)
-t thread count (default: 5)
```
# libs
- ssh2
- weaverjs
